"""empty message

Revision ID: 8f472a009c88
Revises: cd68d64ae9e2
Create Date: 2019-11-28 12:23:45.880994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f472a009c88'
down_revision = 'cd68d64ae9e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('results', sa.Column('score_line', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('results', 'score_line')
    # ### end Alembic commands ###
